#cloud-config
output : { all : '| tee -a /var/log/cloud-init-output.log' }

ssh_keys:
    rsa_private: |
        Private key here

    rsa_public: public key here


packages:
    - git
    - python-pip
    - nginx

runcmd:
    - sed -i -e '$a    IdentityFile /etc/ssh/ssh_host_rsa_key' /etc/ssh/ssh_config
    - restart ssh
    - curl -sSL https://get.docker.com/ubuntu/ | sudo sh
    - pip install fig
    - ssh-keyscan github.com >> /root/.ssh/known_hosts
    - git clone git@github.com:entone/flask-aws-scaffolding.git /app
    - cd /app
    - cp ./config/nginx /etc/nginx/sites-enabled/app
    - rm /etc/nginx/sites-enabled/default
    - service nginx restart
    - fig up -d
